version: "3.8"
services:
  template-db:
    container_name: vesmirna-pomoc-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=vesmirna-pomoc
      - POSTGRES_PASSWORD=pomocNesmirna
    ports:
      - "7654:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
